name: AssassinMiniGamePlugin
version: 1.0
api-version: 1.15
author: Jaymun
main: com.jaymun.AssassinMiniGamePlugin
description: A mini game

commands:
    join:
        usage: /<command>
    quit:
        usage: /<command>